eval "sudo apt-get update"
eval "sudo apt-get install vim"
eval "sudo apt-get install git"
eval "sudo python get-pip.py"
eval "sudo apt-get install python3"
eval "sudo pip install pyOpenSSL ndg-httpsclient pyasn1"
eval "sudo apt-get install curl"
eval "curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash"
