# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('TomatoURL', models.CharField(blank=True, max_length=1024, null=True)),
                ('Actors', models.CharField(blank=True, max_length=1024, null=True)),
                ('BoxOffice', models.CharField(blank=True, max_length=1024, null=True)),
                ('Genres', models.CharField(blank=True, max_length=1024, null=True)),
                ('Director', models.CharField(blank=True, max_length=1024, null=True)),
                ('imdbRating', models.FloatField(blank=True, null=True)),
                ('tomatoRating', models.CharField(blank=True, max_length=32, null=True)),
                ('tomatoUserRating', models.CharField(blank=True, max_length=32, null=True)),
                ('plot', models.CharField(blank=True, max_length=2048, null=True)),
                ('tomatoConsensus', models.CharField(blank=True, max_length=1024, null=True)),
                ('Poster', models.CharField(blank=True, max_length=1024, null=True)),
                ('imdbID', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('tweetID', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('favorite_count', models.IntegerField()),
                ('lang', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=256)),
                ('retweet_count', models.IntegerField()),
                ('user_name', models.CharField(max_length=256)),
                ('user_screen_name', models.CharField(max_length=256)),
                ('user_verified', models.BooleanField()),
                ('imdbID', models.CharField(max_length=1024)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('imdbID', models.CharField(max_length=1024)),
                ('sentimentDate', models.DateTimeField(default=None, null=True)),
                ('sentimentScore', models.FloatField(blank=True, null=True)),
                ('polarity_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
