# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Year', models.IntegerField()),
                ('YomatoURL', models.CharField(max_length=1024)),
                ('Actors', models.CharField(max_length=1024)),
                ('BoxOffice', models.CharField(max_length=1024)),
                ('Genres', models.CharField(max_length=1024)),
                ('Director', models.CharField(max_length=1024)),
                ('imdbRating', models.FloatField()),
                ('tomatoRating', models.CharField(max_length=32)),
                ('tomatorUserRating', models.CharField(max_length=32)),
                ('plot', models.CharField(max_length=2048)),
                ('tomatoConsensus', models.CharField(max_length=1024)),
                ('Poster', models.CharField(max_length=1024)),
                ('imdbID', models.CharField(max_length=1024)),
            ],
        ),
    ]
