# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161030_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('imdbID', models.CharField(max_length=1024)),
                ('sentimentDate', models.DateTimeField(default=None, null=True)),
                ('sentimentScore', models.FloatField(blank=True, null=True)),
                ('polarity_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
