# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 18:20

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161030_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('imdbID', models.CharField(max_length=1024)),
                ('sentimentDate', models.DateField(blank=True, default=None, null=True)),
                ('sentimentScore', models.FloatField(blank=True, null=True)),
                ('positivityScore', models.FloatField(blank=True, null=True)),
                ('negativityScore', models.FloatField(blank=True, null=True)),
                ('neutralityScore', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
