# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_movie_recentvisits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='imdbID',
        ),
        migrations.AddField(
            model_name='tweet',
            name='linkedMovies',
            field=models.ManyToManyField(to='app.Movie'),
        ),
    ]
