# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161201_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tomatoRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tomatoUserRating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
