# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161201_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Awards',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Country',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Production',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Rated',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Released',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Writer',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
