# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161127_2347'),
        ('app', '0010_auto_20161202_1835'),
    ]

    operations = [
    ]
